# Generated by Django 2.2.7 on 2019-12-03 22:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nubank', '0004_auto_20191130_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='NubankBankStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('nubank_id', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('detail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('post_date', models.DateTimeField()),
                ('_type', models.CharField(max_length=200)),
                ('is_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
