# Generated by Django 3.0 on 2019-12-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_enable'),
        ('nubank', '0005_nubankbankstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='nubankbankstatement',
            name='cpf',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='nubankcards',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.FamilyMember', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='nubankitemsetup',
            name='check_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_name', to='mainapp.FamilyMember', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='nubankitemsetup',
            name='check_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nubankitemsetup',
            name='check_value_operator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nubankitemsetup',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nubankitemsetup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='nubankitemsetup',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.FamilyMember', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='nubankitemsetup',
            name='type_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TypeEntry', verbose_name='Type'),
        ),
    ]
