# Generated by Django 2.2.6 on 2019-10-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Enable?'),
        ),
    ]
