# Generated by Django 2.0.5 on 2018-09-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='FullCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='', max_length=70, verbose_name='Comando')),
                ('entry_date', models.BooleanField(verbose_name='Data de Lançamento: Usa data do dia?')),
                ('payment_date', models.IntegerField(choices=[(1, 'Data do Dia'), (2, 'Data do Cartão (15)'), (3, 'Perguntar')], default=1, verbose_name='Data de Pagamento')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Débito')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Crédito')),
                ('description', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Descrição')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Categoria')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.FamilyMember', verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_included_date_time', models.DateTimeField(auto_now=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('payment_date_time', models.DateTimeField(null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Débito')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Crédito')),
                ('description', models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='Descrição')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Categoria')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.FamilyMember', verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(default='', max_length=70, verbose_name='Comando')),
                ('values', models.CharField(default='', max_length=4000, verbose_name='Valores')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='records',
            name='type_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TypeEntry', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='fullcommand',
            name='type_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.TypeEntry', verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['db_included_date_time'], name='db_included_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['create_date_time'], name='create_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['payment_date_time'], name='payment_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['category'], name='category_idx'),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='records',
            index=models.Index(fields=['type_entry'], name='type_entry_idx'),
        ),
    ]
