# Generated by Django 2.0.5 on 2018-09-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullcommand',
            name='payment_date',
            field=models.IntegerField(choices=[(1, 'Data do Dia'), (2, 'Data do Cartão (15)'), (3, 'Perguntar'), (4, 'Dia Seguinte'), (5, 'Mês Seguinte'), (6, 'Dia 5 mês vigente'), (7, 'Dia 5 mês que vem')], default=1, verbose_name='Data de Pagamento'),
        ),
    ]
