# Generated by Django 2.1.1 on 2018-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180929_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullcommand',
            name='payment_date',
            field=models.IntegerField(choices=[(1, 'Data do Dia'), (2, 'Data do Cartão (15)'), (3, 'Perguntar'), (4, 'Dia Seguinte'), (5, 'Mês Seguinte'), (6, 'Dia 5 mês vigente'), (7, 'Dia 5 mês que vem'), (8, 'Crédito Parcelado')], default=1, verbose_name='Data de Pagamento'),
        ),
    ]
