# Generated by Django 2.1.1 on 2018-10-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180929_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleCommand',
        ),
    ]
