# Generated by Django 2.2.4 on 2019-09-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_simplecommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullcommand',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Descrição'),
        ),
    ]
