# Generated by Django 2.2.8 on 2020-06-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='BrokersNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('brokerage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('settlement_fee', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('Emonuments_fee', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokes_note.Broker')),
            ],
            options={
                'unique_together': {('broker', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('paper', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BrokersNoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('buy_or_sell', models.CharField(max_length=1)),
                ('credit_or_debit', models.CharField(max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokes_note.Company')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokes_note.BrokersNote')),
            ],
        ),
    ]
